name: documentation
stages:
  - name: request
    type: request
    gate:
      type: auto

  - name: implementation
    type: implementation
    gate:
      type: chain_complete

  - name: completion
    type: review
    gate:
      type: human_approval
      prompt: "Documentation updated. Approve?"
