name: standard
displayName: Standard Workflow
description: Execute a committed request through design, implementation, and completion
stages:
  - name: planning
    type: design
    roleId: orchestration
    gate:
      type: human_approval
      prompt: "Design chains ready. Proceed?"
    onEnter:
      - type: file_move
        from: "docs/requests/change-requests/todo/{{requestId}}.md"
        to: "docs/requests/change-requests/doing/{{requestId}}.md"

  - name: design
    type: implementation
    roleId: design
    gate:
      type: chain_complete
    onEnter:
      - type: command
        command: "choragen chain:spawn-agents {{chainIds}}"

  - name: impl-planning
    type: design
    roleId: orchestration
    gate:
      type: human_approval
      prompt: "Implementation chains ready. Proceed?"

  - name: implementation
    type: implementation
    roleId: implementation
    gate:
      type: chain_complete
    onEnter:
      - type: command
        command: "choragen chain:spawn-agents {{chainIds}}"

  - name: verification
    type: verification
    roleId: system
    gate:
      type: verification_pass
      commands:
        - "pnpm build"
        - "pnpm test"
        - "pnpm lint"

  - name: commit
    type: implementation
    roleId: commit
    gate:
      type: human_approval
      prompt: "Commits ready. Push?"

  - name: request-review
    type: review
    roleId: review
    gate:
      type: human_approval
      prompt: "Request complete. Approve and push?"

  - name: completion
    type: review
    roleId: control
    gate:
      type: human_approval
      prompt: "Final approval. Close request?"
    onExit:
      - type: file_move
        from: "docs/requests/change-requests/doing/{{requestId}}.md"
        to: "docs/requests/change-requests/done/{{requestId}}.md"
      - type: command
        command: "choragen request:close {{requestId}}"
      - type: command
        command: "choragen chain:archive {{chainIds}}"
