name: standard
stages:
  - name: request
    type: request
    gate:
      type: human_approval
      prompt: "CR created. Proceed to design?"

  - name: design
    type: design
    gate:
      type: human_approval
      prompt: "Design complete. Proceed to implementation?"

  - name: implementation
    type: implementation
    gate:
      type: chain_complete

  - name: verification
    type: verification
    gate:
      type: verification_pass
      commands:
        - "pnpm build"
        - "pnpm test"
        - "pnpm lint"

  - name: completion
    type: review
    gate:
      type: human_approval
      prompt: "All checks pass. Approve and merge?"
