// ADR: ADR-015-commit-audit-mechanism
// Change request: docs/requests/change-requests/doing/CR-20251213-003-commit-audit.md

/**
 * Audit findings domain types.
 *
 * These types represent intermediate audit data produced by audit tasks
 * before feedback compilation converts them into feedback items.
 */

export const AUDIT_SEVERITIES = [
  "critical",
  "major",
  "minor",
  "info",
] as const;

/**
 * Severity levels for audit findings, ordered from highest to lowest urgency.
 */
export type AuditSeverity = (typeof AUDIT_SEVERITIES)[number];

export const AUDIT_TASK_TYPES = [
  "security-audit",
  "architecture-audit",
  "standards-audit",
  "documentation-audit",
  "testing-audit",
  "traceability-audit",
  "performance-audit",
  "review",
] as const;

/**
 * Supported audit task types that produce findings in the audit chain.
 */
export type AuditTaskType = (typeof AUDIT_TASK_TYPES)[number];

/**
 * Individual finding produced by an audit task prior to feedback compilation.
 */
export interface AuditFinding {
  /** Severity of the finding (critical > major > minor > info). */
  severity: AuditSeverity;
  /** Finding category (e.g., "secrets", "naming", "documentation"). */
  category: string;
  /** Human-readable description of the finding. */
  description: string;
  /** Optional file path associated with the finding. */
  file?: string;
  /** Optional line number associated with the finding. */
  line?: number;
  /** Optional recommended remediation or next step. */
  suggestion?: string;
}

/**
 * Collection of findings generated by a specific audit task type.
 */
export interface AuditTaskFindings {
  /** Audit task type that produced these findings. */
  taskType: AuditTaskType;
  /** Findings produced by the task. */
  findings: AuditFinding[];
}

/**
 * Chain context container for accumulating audit task findings (tasks 1-8).
 */
export interface AuditChainContext {
  /** All audit task findings captured before feedback compilation. */
  taskFindings: AuditTaskFindings[];
}
